---
title: "Simstudy Hypertension Test"
format: html
editor: visual
---

## SimStudy with ONS Hypertension Data

```{r message=F, warning=F}
library(readxl)
library(simstudy)
library(tidyverse)
```

Read the data

```{r}
characteristics.aggregate <- read_xlsx("characteristicsundiagnosedanduncontrolledhypertensiondataset.xlsx", sheet = "Table 5",skip = 11 )

```

Create a simulated dataset definition

```{r}
def <- defData(varname = "gender", formula = "0.508;0.492", variance = "female;male", dist="categorical")



```

Generate the simulated data

```{r}

set.seed(123)
hypertension.simulated.data <- genData(21490, def)

```

Use a conditional variable for the age groups

```{r}

# Total columns (Sheet 5)

defAge <- defCondition(
  condition = "gender == 'female'", 
  formula = "0.12;0.16;0.15;0.17;0.15;0.13;0.11",
  variance = "16-24 years;25-34 years;35-44 years;45-54 years;55-64 years;65-74 years;75 years and over",
  dist = "categorical"
)
defAge <- defCondition(defAge,
  condition = "gender == 'male'",
   formula = "0.14;0.16;0.16;0.17;0.15;0.13;0.09",
   variance = "16-24 years;25-34 years;35-44 years;45-54 years;55-64 years;65-74 years;75 years and over",
   dist = "categorical"
)


# Add column

hypertension.simulated.data <- addCondition(defAge, hypertension.simulated.data, "agegroup")



```

Now add 1 0r 0 based on Hypertension prevalence given age

```{r}

# Hypertension prevalence given age (Sheet 1 / Sheet 5)

females <<- 0.508

defHypertension <- defCondition(
  condition = "gender == 'female' & agegroup == '16-24years'", 
  formula = "0.02 * ..females",
  dist = "binary"
)

defHypertension <- defCondition(defHypertension,
  condition = "gender == 'female' & agegroup == '25-34years'",
  formula = "0.07 * ..females",
  dist = "binary"
)

defHypertension <- defCondition(defHypertension,
  condition = "gender == 'female' & agegroup == '35-44years'",
  formula = "0.09 * ..females",
  dist = "binary"
)

defHypertension <- defCondition(defHypertension,
  condition = "gender == 'female' & agegroup == '45-54years'",
  formula = "0.17 * ..females",
  dist = "binary"
)

defHypertension <- defCondition(defHypertension,
  condition = "gender == 'female' & agegroup == '55-64years'",
  formula = "0.21 * ..females",
  dist = "binary"
)

defHypertension <- defCondition(defHypertension,
  condition = "gender == 'female' & agegroup == '65-74years'",
  formula = "0.25 * ..females",
  dist = "binary"
)

defHypertension <- defCondition(defHypertension,
  condition = "gender == 'female' & agegroup == '75yearsandover'",
  formula = "0.21 * ..females",
  dist = "binary"
)


# Add column

hypertension.simulated.data <- addCondition(defHypertension, hypertension.simulated.data, "undiagnosed.hypertension")


```

Now, all other variables can be added as follows, using Table 1 and 2

```{r}
# Hypertension prevalence given self-reported health


defHealth <- defCondition(
  condition = "gender == 'female' & undiagnosed.hypertension == 1", 
  formula = "0.74;0.18;0.09",
  variance = "Very good or good;Fair;Bad or very bad",
  dist = "categorical"
)

defHealth <- defCondition(defHealth,
  condition = "gender == 'female' & undiagnosed.hypertension == 0", 
  formula = "0.75;0.18;0.07",
  variance = "Very good or good;Fair;Bad or very bad",
  dist = "categorical"
)


hypertension.simulated.data <- addCondition(defHealth, hypertension.simulated.data, "selfreported.health")

```


```{r}

#Check numbers for totals

hypertension.simulated.data |> group_by(gender,agegroup ) |> summarise(n = n())

```

```{r}

## check numbers of undiagnosed hypertension

hypertension.simulated.data |> filter(undiagnosed.hypertension == 1) |> group_by(gender,agegroup ) |> summarise(n = n())


```

```{r}

# Check numbers of self-reported health

hypertension.simulated.data |> drop_na(selfreported.health) |> filter(undiagnosed.hypertension == 1) |> group_by(selfreported.health ) |> summarise(n = n())

```